num1 = float(input('give me a number: '))
num2 = float(input('give me second number: '))
num3 = float(input('give me third number: '))
num4 = float(input('give me fourth number: '))
print( (num1 - num2) * num3 / num4 )